### ISSUE TITLE
Irrelevant file

### ISSUE THREAD

**Issue by HwngPham** [mjboy1412/NewsInsider#1]
https://github.com/mjboy1412/NewsInsider/blob/9a381f1286a71c5d4eb311516ab0c9ad39227aab/scss/index.css#L1

This file is not supposed to be stored in scss folder. If you do have a clear purpose, please leave comment note for explanation. If you do not, please remove the file.

**Comment by mjboy1412** [comment]
this is a backup by Koala (SASS tool) has created earlier

> [NewsInsider/scss/index.css](https://github.com/mjboy1412/NewsInsider/blob/9a381f1286a71c5d4eb311516ab0c9ad39227aab/scss/index.css#L1)
> 
> Line 1 in [9a381f1](/mjboy1412/NewsInsider/commit/9a381f1286a71c5d4eb311516ab0c9ad39227aab)
> 
>  html { 
> This file is not supposed to be stored in scss folder. If you do have a clear purpose, please leave comment note for explanation. If you do not, please remove the file.

**Comment by HwngPham** [comment]
if you want to keep it in local, list this file to `.gitignore`
