### ISSUE TITLE
Font size inconsistency

### ISSUE THREAD

**Issue by HwngPham** [mjboy1412/NewsInsider#13]
https://github.com/mjboy1412/NewsInsider/blob/9a381f1286a71c5d4eb311516ab0c9ad39227aab/scss/partials/feedback-wrapper/this/_feedback-wrapper.scss#L37

Create a set of fixed size variables and use them instead of casually hard code the font size.

**Comment by mjboy1412** [comment]
the feed back use only appear on pc screen that's the reason why it has fixed font-size
