### ISSUE TITLE
Fuck this loop

### ISSUE THREAD

**Issue by HwngPham** [mjboy1412/NewsInsider#22]
https://github.com/mjboy1412/NewsInsider/blob/9a381f1286a71c5d4eb311516ab0c9ad39227aab/js/main.js#L2

You can do better than this...

**Comment by mjboy1412** [comment]
issue #22 fixed

> [NewsInsider/js/main.js](https://github.com/mjboy1412/NewsInsider/blob/9a381f1286a71c5d4eb311516ab0c9ad39227aab/js/main.js#L2)
> 
> Line 2 in [9a381f1](/mjboy1412/NewsInsider/commit/9a381f1286a71c5d4eb311516ab0c9ad39227aab)
> 
>  var stateCheck = setInterval(() => { 
> You can do better than this...
