### ISSUE TITLE
File naming

### ISSUE THREAD

**Issue by HwngPham** [mjboy1412/NewsInsider#23]
![bbbbb](https://user-images.githubusercontent.com/15817110/50721423-dfd5bc00-10f1-11e9-9fcd-19803734b5c7.png)

You can naming the file like this
- functions.js or utils.js
- globals.js
- main.js

**Comment by mjboy1412** [comment]
fix

> ![bbbbb](https://user-images.githubusercontent.com/15817110/50721423-dfd5bc00-10f1-11e9-9fcd-19803734b5c7.png)
> 
> You can naming the file like this
> 
> * functions.js or utils.js
> * globals.js
> * main.js
