### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by HwngPham** [mjboy1412/NewsInsider#24]
https://github.com/mjboy1412/NewsInsider/blob/9a381f1286a71c5d4eb311516ab0c9ad39227aab/js/all_function.js#L40

This function causes performance leaking.
Use css rule instead.
`text-overflow: ellipsis;`

**Comment by mjboy1412** [comment]
not working on firefox

**Comment by mjboy1412** [comment]
> not working on firefox

**Comment by mjboy1412** [comment]
> [NewsInsider/js/all_function.js](https://github.com/mjboy1412/NewsInsider/blob/9a381f1286a71c5d4eb311516ab0c9ad39227aab/js/all_function.js#L40)
> 
> Line 40 in [9a381f1](/mjboy1412/NewsInsider/commit/9a381f1286a71c5d4eb311516ab0c9ad39227aab)
> 
>  function text_truncate() { 
> This function causes performance leaking.
> Use css rule instead.
> `text-overflow: ellipsis;`

this function will break the loop when the text is truncated at 100th character each text field. Btw, text-overflow: ellipsis is not supported on firefox.
